name: CI – Repo Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check structure
        run: ./scripts/check_repo.sh
